annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: GameServers
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 17.4.2
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: "This Chart will download and install Neverwinter Nights: Enhanced Edition and run it (by default this Chart has a MariaDB and Redis Server integrated)."
home: https://truecharts.org/charts/stable/neverwinternights-ee
icon: https://truecharts.org/img/hotlink-ok/chart-icons/neverwinternights-ee.png
keywords:
  - neverwinternights-ee
  - GameServers
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: neverwinternights-ee
sources:
  - https://www.beamdog.com/games/neverwinter-nights-enhanced/
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/neverwinternights-ee
  - https://hub.docker.com/r/ich777/nwnee-server
type: application
version: 4.2.0
