annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 5.5.2
dependencies:
  - name: common
    version: 17.5.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: TagSpaces is an offline, open source, document manager with tagging support.
home: https://truecharts.org/charts/stable/tagspaces
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tagspaces.png
keywords:
  - tagspaces
  - documents
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: tagspaces
sources:
  - https://github.com/tagspaces/tagspaces
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/tagspaces
  - https://hub.docker.com/r/tagspaces/tagspaces-lite-web
type: application
version: 2.3.0
