annotations:
  truecharts.org/category: utilities
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 24.4.1
dependencies:
  - name: common
    version: 23.0.9
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: An open source time-tracker with an interactive user experience and powerful reporting.
home: https://truecharts.org/charts/stable/timetagger
icon: https://truecharts.org/img/hotlink-ok/chart-icons/timetagger.webp
keywords:
  - time
  - timetagger
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: timetagger
sources:
  - https://ghcr.io/almarklein/timetagger
  - https://github.com/almarklein/timetagger
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/timetagger
  - https://timetagger.app
type: application
version: 7.0.8
