annotations:
  truecharts.org/category: Crypto
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 0.18.3.3
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Chart to run a monero full network node
home: https://truecharts.org/charts/stable/monero-node
icon: https://truecharts.org/img/hotlink-ok/chart-icons/monero-node.webp
keywords:
  - monero-node
  - Crypto
  - Tools-Utilities
  - Network-Other
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: monero-node
sources:
  - https://ghcr.io/sethforprivacy/simple-monerod
  - https://github.com/kannix/monero-full-node
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/monero-node
type: application
version: 7.0.14
