annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 4.8.7.0
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Emby Server is a home media server
home: https://truecharts.org/charts/stable/emby
icon: https://truecharts.org/img/hotlink-ok/chart-icons/emby.webp
keywords:
  - jellyfin
  - plex
  - emby
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: emby
sources:
  - https://ghcr.io/geek-cookbook/emby
  - https://github.com/linuxserver/docker-emby.git
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/emby
type: application
version: 19.0.11
