annotations:
  truecharts.org/category: Cloud
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Synchronized video viewing with chat and other features. Lightweight modern implementation and very easy way to run locally.
home: https://truecharts.org/charts/stable/synctube
icon: https://truecharts.org/img/hotlink-ok/chart-icons/synctube.webp
keywords:
  - synctube
  - Cloud
  - Productivity
  - Tools-Utilities
  - MediaApp-Video
  - MediaServer-Video
  - Network-Web
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: synctube
sources:
  - https://github.com/RblSb/SyncTube
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/synctube
  - https://hub.docker.com/r/littlestache/synctube
type: application
version: 8.0.8
