annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: Crypto
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 18.0.1
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Chart to run a monero full network node
home: https://truecharts.org/charts/stable/monero-node
icon: https://truecharts.org/img/hotlink-ok/chart-icons/monero-node.png
keywords:
  - monero-node
  - Crypto
  - Tools-Utilities
  - Network-Other
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: monero-node
sources:
  - https://github.com/kannix/monero-full-node
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/monero-node
  - https://hub.docker.com/r/kannix/monero-full-node
type: application
version: 5.1.0
