annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: AI
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 0.1.32
dependencies:
  - name: common
    version: 20.3.12
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Get up and running with large language models locally.
home: https://truecharts.org/charts/stable/ollama
icon: https://truecharts.org/img/hotlink-ok/chart-icons/ollama.webp
keywords:
  - ollama
  - language-models
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: ollama
sources:
  - https://github.com/ollama/ollama
  - https://github.com/open-webui/open-webui
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/ollama
  - https://hub.docker.com/r/ollama/ollama
  - https://ghcr.io/open-webui/open-webui
type: application
version: 5.4.26
