annotations:
  truecharts.org/category: Tools-Utilities
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 23.0.9
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: rmlint finds space waste and other broken things on your filesystem and offers to remove it.
home: https://truecharts.org/charts/stable/rmlint
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rmlint.webp
keywords:
  - rmlint
  - Tools-Utilities
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: rmlint
sources:
  - https://github.com/sahib/rmlint
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/rmlint
  - https://hub.docker.com/r/bobbintb/docker-rmlint-unraid
type: application
version: 6.0.7
