annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: file-storage
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 11.0.5
dependencies:
  - name: common
    version: 17.4.2
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: mariadb
    version: 12.2.1
    repository: oci://tccr.io/truecharts
    condition: mariadb.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Reliable and Performant File Sync and Share Solution
home: https://truecharts.org/charts/stable/seafile
icon: https://truecharts.org/img/hotlink-ok/chart-icons/seafile.png
keywords:
  - seafile
  - files
  - cloud
  - file-storage
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: seafile
sources:
  - https://seafile.com
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/seafile
  - https://hub.docker.com/r/seafileltd/seafile-mc
type: application
version: 4.3.0
