annotations:
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 4.5.0
dependencies:
  - name: common
    version: 23.0.9
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: IRC Highway eBook Downloads.
home: https://truecharts.org/charts/stable/openbooks
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openbooks.webp
keywords:
  - openbooks
  - media
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: openbooks
sources:
  - https://github.com/evan-buss/openbooks
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/openbooks
  - https://hub.docker.com/r/evanbuss/openbooks
type: application
version: 5.0.8
