annotations:
  truecharts.org/category: Other
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: main
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Socials is a single-page website that stores all your social media and personal websites to share. It is similar to tappy.tech, sociallinks.co, and linktr.ee, but open-source and built using Typescript, Sass, Express.js and EJS. Self-hosting or publishing as a static website or Chart is recommended!
home: https://truecharts.org/charts/stable/socials
icon: https://truecharts.org/img/hotlink-ok/chart-icons/socials.webp
keywords:
  - socials
  - Other
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: socials
sources:
  - https://ghcr.io/diamkil/socials
  - https://github.com/diamkil/socials
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/socials
  - https://registry.hub.docker.com/r/diamkil/socials/
type: application
version: 6.0.8
