annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: GameServers
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 4.2.3
dependencies:
  - name: common
    version: 17.4.2
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Crafty Controller is a Minecraft Server Control Panel / Launcher.
home: https://truecharts.org/charts/stable/crafty-4
icon: https://truecharts.org/img/hotlink-ok/chart-icons/crafty-4.png
keywords:
  - crafty-4
  - GameServers
  - Other
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: crafty-4
sources:
  - https://craftycontrol.com/
  - https://gitlab.com/crafty-controller/crafty-4
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/crafty-4
type: application
version: 6.2.0
