annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 2.17.01
dependencies:
  - name: common
    version: 20.3.12
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Audio/Video library transcoding automation
home: https://truecharts.org/charts/stable/tdarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tdarr.webp
keywords:
  - encode
  - media
  - tdarr
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: tdarr
sources:
  - https://github.com/HaveAGitGat/Tdarr
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/tdarr
  - https://hub.docker.com/r/haveagitgat/tdarr
type: application
version: 9.8.14
