annotations:
  truecharts.org/category: Productivity
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: ROOT is a framework for data processing, born at CERN, at the heart of the research on high-energy physics. Every day, thousands of physicists use ROOT applications to analyze their data or to perform simulations.
home: https://truecharts.org/charts/stable/root
icon: https://truecharts.org/img/hotlink-ok/chart-icons/root.webp
keywords:
  - root
  - Productivity
  - Tools-Utilities
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: root
sources:
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/root
  - https://hub.docker.com/r/bgameiro/arch-cern-root
  - https://root.cern/
type: application
version: 6.0.8
