annotations:
  truecharts.org/category: incubator
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 8.0.36
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: MySQL Workbench is a unified visual tool for database architects, developers and DBAs.
home: https://truecharts.org/charts/stable/mysql-workbench
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mysql-workbench.webp
keywords:
  - mysql-workbench
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mysql-workbench
sources:
  - https://ghcr.io/linuxserver/mysql-workbench
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/mysql-workbench
type: application
version: 10.0.13
