annotations:
  truecharts.org/category: GameServers
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: citadelfwf
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: This Chart will download and install SteamCMD. It will also install Citadel - Forged with Fire and run it.
home: https://truecharts.org/charts/stable/citadel-forgedwithfire
icon: https://truecharts.org/img/hotlink-ok/chart-icons/citadel-forgedwithfire.webp
keywords:
  - citadel-forgedwithfire
  - GameServers
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: citadel-forgedwithfire
sources:
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/citadel-forgedwithfire
  - https://hub.docker.com/r/ich777/steamcmd
  - https://www.steampowered.com/
type: application
version: 6.0.9
