annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: Productivity
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: stable
dependencies:
  - name: common
    version: 17.5.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A safe and private place for your life's work.
home: https://truecharts.org/charts/stable/standardnotes-web
icon: https://truecharts.org/img/hotlink-ok/chart-icons/standardnotes-web.png
keywords:
  - standardnotes-web
  - Productivity
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: standardnotes-web
sources:
  - https://standardnotes.org/
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/standardnotes-web
  - https://hub.docker.com/r/standardnotes/web
type: application
version: 4.3.0
