annotations:
  max_scale_version: 24.04.0
  min_scale_version: 23.10.0
  truecharts.org/category: custom
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: premium
apiVersion: v2
appVersion: 0.21.1155
dependencies:
  - name: common
    version: 20.3.12
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Advanced tool to create your own TrueCharts-based Charts
home: https://truecharts.org/charts/premium/custom-app
icon: https://truecharts.org/img/hotlink-ok/chart-icons/custom-app.webp
keywords:
  - custom
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: custom-app
sources:
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/premium/custom-app
  - https://ghcr.io/linuxserver/jackett
type: application
version: 12.8.14
