annotations:
  truecharts.org/category: Productivity
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: latest
dependencies:
  - name: common
    version: 23.0.9
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A simple, self-hosted, encrypted Markdown note-taking app built with Vue 3, and Express.
home: https://truecharts.org/charts/stable/mininote
icon: https://truecharts.org/img/hotlink-ok/chart-icons/mininote.webp
keywords:
  - mininote
  - Productivity
  - Tools-Utilities
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: mininote
sources:
  - https://github.com/muety/mininote
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/mininote
  - https://hub.docker.com/r/n1try/mininote
type: application
version: 6.0.8
