annotations:
  truecharts.org/category: Cloud
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 6.2.0
dependencies:
  - name: common
    version: 23.0.9
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: FileShelter is a self-hosted software that allows you to easily share files over the Internet. Just upload one or more files and get an URL back!
home: https://truecharts.org/charts/stable/fileshelter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/fileshelter.webp
keywords:
  - fileshelter
  - Cloud
  - Tools-Utilities
  - Network-Web
  - Network-FTP
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: fileshelter
sources:
  - https://github.com/epoupon/fileshelter
  - https://github.com/rogersbernat/truecharts-charts/tree/master/charts/stable/fileshelter
  - https://hub.docker.com/r/epoupon/fileshelter
type: application
version: 7.0.8
